html:
  vnu: https://av.mitsue.com
  charset: utf-8
  include: '**/*.html'
  ignore:
    - '**/node_modules/**'
    - 'node_modules/**'
    - 'docs/_mlc/**'
    - 'docs/**/inc/**'
css:
  vnu: https://av.mitsue.com
  charset: utf-8
  include: 'docs/common/css/main.css'
  ignore:
    - '**/node_modules/**'
    - 'docs/**'
